[package]
name = "wslu-ng"
version = "0.0.1"
authors = ["Jinming Wu, Patrick <me@patrickwu.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
